# AvatarPvP Config
# Ask drtshock if you need help or have issues.
# $35 upfront and 20% of future gains.
# I will keep this plugin updated in the future :)
##################################################
############### Config starts here ###############
version: 0.1